#!/usr/bin/env bash
# Install the Pulse PM home sync server as an always-on systemd user service.
#
#   bash sync-server/install-service.sh                  # install + start (port 8091)
#   PORT=8092 DATA=~/pulse-pm-sync.json bash sync-server/install-service.sh
#   bash sync-server/install-service.sh --print          # show the unit file, install nothing
#   bash sync-server/install-service.sh --uninstall      # stop + remove the service
#
# After installing, the server starts on every login and restarts on failure.
# Logs:  journalctl --user -u pulse-pm-sync -f
set -euo pipefail

SERVICE="pulse-pm-sync.service"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PORT="${PORT:-8091}"
DATA="${DATA:-$ROOT/sync-server/pulse-pm-sync.json}"
UNIT_DIR="$HOME/.config/systemd/user"
UNIT_FILE="$UNIT_DIR/$SERVICE"

usage() {
  echo "Usage: bash sync-server/install-service.sh [--print] [--uninstall]"
  echo "Env:   PORT=8091  DATA=$ROOT/sync-server/pulse-pm-sync.json"
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then usage; exit 0; fi

if [[ "${1:-}" == "--uninstall" ]]; then
  systemctl --user disable --now "$SERVICE" 2>/dev/null || true
  rm -f "$UNIT_FILE"
  systemctl --user daemon-reload 2>/dev/null || true
  echo "Removed $SERVICE."
  exit 0
fi

BUN="$(command -v bun || true)"
if [[ -z "$BUN" ]]; then
  echo "error: 'bun' not found on PATH. Install it first: https://bun.sh" >&2
  exit 1
fi

if ! systemctl --user list-units >/dev/null 2>&1; then
  echo "error: systemd user services unavailable. Run the server manually instead:" >&2
  echo "  bun run sync:server" >&2
  exit 1
fi

UNIT="# Generated by pulse-pm sync-server/install-service.sh — do not edit by hand.
[Unit]
Description=Pulse PM home sync server (phone <-> PC auto sync)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$ROOT
ExecStart=$BUN $ROOT/sync-server/server.ts
Environment=PORT=$PORT
Environment=SYNC_DATA=$DATA
Restart=always
RestartSec=3

[Install]
WantedBy=default.target
"

if [[ "${1:-}" == "--print" ]]; then
  printf '%s' "$UNIT"
  exit 0
fi

mkdir -p "$UNIT_DIR"
printf '%s' "$UNIT" > "$UNIT_FILE"
systemctl --user daemon-reload
systemctl --user enable --now "$SERVICE"

echo
echo "Installed + started $SERVICE (port $PORT, data $DATA)."
echo "Status: systemctl --user status $SERVICE"
echo "Logs:   journalctl --user -u $SERVICE -f"
echo
echo "On your LAN this PC is reachable at (enter one in the app's ⇄ Sync dialog):"
hostname -I 2>/dev/null | tr ' ' '\n' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | sed "s|^|  http://|" | sed "s|$|:$PORT|" || true
echo "On this PC itself use: http://127.0.0.1:$PORT"
