#!/usr/bin/env bash
# Install the Pulse PM home servers as always-on systemd user services:
#   pulse-pm-sync.service  SQLite sync server (phone <-> PC auto sync)
#   pulse-pm-web.service   built web UI from dist/ (phone browser, LAN)
#
#   bash sync-server/install-service.sh                  # install + start both (8091 + 8080)
#   WEB=0 bash sync-server/install-service.sh            # sync server only
#   PORT=8092 WEB_PORT=8081 DATA=~/hive-pm-sync.db bash sync-server/install-service.sh
#   bash sync-server/install-service.sh --print          # show the unit files, install nothing
#   bash sync-server/install-service.sh --uninstall      # stop + remove both services
#
# DATA is the SQLite database file (SYNC_DB). An old hive/pulse-pm-sync.json
# next to it is migrated automatically on first start.
#
# After installing, the servers start on every login (linger enabled, so they
# survive logout) and restart on failure.
# Logs:  journalctl --user -u pulse-pm-sync -f
#        journalctl --user -u pulse-pm-web -f
set -euo pipefail

SERVICE="pulse-pm-sync.service"
WEB_SERVICE="pulse-pm-web.service"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PORT="${PORT:-8091}"
WEB_PORT="${WEB_PORT:-8080}"
WEB="${WEB:-1}"
DATA="${DATA:-$ROOT/sync-server/hive-pm-sync.db}"
UNIT_DIR="$HOME/.config/systemd/user"
UNIT_FILE="$UNIT_DIR/$SERVICE"
WEB_UNIT_FILE="$UNIT_DIR/$WEB_SERVICE"

usage() {
  echo "Usage: bash sync-server/install-service.sh [--print] [--uninstall] [--no-web]"
  echo "Env:   PORT=8091 WEB_PORT=8080 WEB=1 DATA=$ROOT/sync-server/hive-pm-sync.db"
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then usage; exit 0; fi

if [[ "${1:-}" == "--no-web" ]]; then WEB=0; shift; fi

if [[ "${1:-}" == "--uninstall" ]]; then
  systemctl --user disable --now "$SERVICE" "$WEB_SERVICE" 2>/dev/null || true
  rm -f "$UNIT_FILE" "$WEB_UNIT_FILE"
  systemctl --user daemon-reload 2>/dev/null || true
  echo "Removed $SERVICE and $WEB_SERVICE."
  exit 0
fi

BUN="$(command -v bun || true)"
if [[ -z "$BUN" ]]; then
  echo "error: 'bun' not found on PATH. Install it first: https://bun.sh" >&2
  exit 1
fi

if ! systemctl --user list-units >/dev/null 2>&1; then
  echo "error: systemd user services unavailable. Run the server manually instead:" >&2
  echo "  bun run sync:server" >&2
  exit 1
fi

UNIT="# Generated by pulse-pm sync-server/install-service.sh — do not edit by hand.
[Unit]
Description=Pulse PM home sync server (phone <-> PC auto sync)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$ROOT
ExecStart=$BUN $ROOT/sync-server/server.ts
Environment=PORT=$PORT
Environment=SYNC_DB=$DATA
Restart=always
RestartSec=3

[Install]
WantedBy=default.target
"

# Same `vite preview` daemon start-prod.sh uses — serves the built dist/.
WEB_UNIT="# Generated by pulse-pm sync-server/install-service.sh — do not edit by hand.
[Unit]
Description=Pulse PM web UI (LAN browser app)
After=network-online.target pulse-pm-sync.service
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$ROOT
ExecStart=$BUN $ROOT/node_modules/vite/bin/vite.js preview --host 0.0.0.0 --port $WEB_PORT --strictPort
Restart=always
RestartSec=3

[Install]
WantedBy=default.target
"

if [[ "${1:-}" == "--print" ]]; then
  printf '%s\n%s' "$UNIT" "$WEB_UNIT"
  exit 0
fi

mkdir -p "$UNIT_DIR"
printf '%s' "$UNIT" > "$UNIT_FILE"
# Hand ports over: stop anything start-prod.sh manages, else systemd flaps on EADDRINUSE.
for f in "$ROOT/.run/sync-server.pid" "$ROOT/.run/web.pid"; do
  if [[ -f "$f" ]]; then
    pid="$(cat "$f")"
    if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then kill "$pid" 2>/dev/null || true; fi
    rm -f "$f"
  fi
done
sleep 2
systemctl --user daemon-reload
systemctl --user enable --now "$SERVICE"

if [[ "$WEB" == "1" ]]; then
  # dist/ must exist for `vite preview`; build once if missing.
  [[ -f "$ROOT/dist/index.html" ]] || bun run --cwd "$ROOT" build
  printf '%s' "$WEB_UNIT" > "$WEB_UNIT_FILE"
  systemctl --user daemon-reload
  systemctl --user enable --now "$WEB_SERVICE"
fi
# Survive logout + start after reboot without a login session hanging around.
loginctl enable-linger "$USER" 2>/dev/null || true

echo
echo "Installed + started $SERVICE (port $PORT, data $DATA)."
if [[ "$WEB" == "1" ]]; then
  echo "Installed + started $WEB_SERVICE (port $WEB_PORT, dist/ in $ROOT)."
fi
echo "Status: systemctl --user status $SERVICE $WEB_SERVICE"
echo "Logs:   journalctl --user -u $SERVICE -f"
echo "        journalctl --user -u $WEB_SERVICE -f"
echo
echo "On your LAN this PC is reachable at (enter one in the app's ⇄ Sync dialog):"
hostname -I 2>/dev/null | tr ' ' '\n' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | sed "s|^|  http://|" | sed "s|$|:$PORT|" || true
echo "On this PC itself use: http://127.0.0.1:$PORT"
